field: 3fe36747-cd19-43f4-ab43-3990abff9e6f # Card
fieldLayouts:
  19a68dde-019c-4874-8991-22fa8aa7912c:
    tabs:
      -
        elements:
          -
            fieldUid: 57d5a4d4-ec7a-49df-8759-4c678060fb0b # cardImage
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5e00612a-24b9-494d-a4d8-eae8e7a1be6d # Card Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1f03427e-0787-4cec-a019-10df1ed18b0d # Button text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1f03427e-0787-4cec-a019-10df1ed18b0d: # Button text
    columnSuffix: rvzlcred
    contentColumnType: text
    fieldGroup: null
    handle: cardButtonText
    instructions: ''
    name: 'Button text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5e00612a-24b9-494d-a4d8-eae8e7a1be6d: # Card Title
    columnSuffix: yhzfllbw
    contentColumnType: text
    fieldGroup: null
    handle: cardTitle
    instructions: ''
    name: 'Card Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  57d5a4d4-ec7a-49df-8759-4c678060fb0b: # cardImage
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cardImage
    instructions: ''
    name: cardImage
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:9a010872-6648-4d56-aebc-be463321e508' # assets
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:9a010872-6648-4d56-aebc-be463321e508' # assets
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: card
name: Card
sortOrder: 1
