field: 549b062c-daec-43d3-8b33-61d5a72df5e0 # Footer contact
fieldLayouts:
  59cbbc30-1edb-4661-9266-66bec1d2be2d:
    tabs:
      -
        elements:
          -
            fieldUid: 7105d923-f6d7-4ecb-8547-33e9a1576cdb # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b51b712a-f40c-4a77-b637-ef850aac7471 # text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7105d923-f6d7-4ecb-8547-33e9a1576cdb: # Logo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: logo
    instructions: ''
    name: Logo
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:9a010872-6648-4d56-aebc-be463321e508' # assets
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:9a010872-6648-4d56-aebc-be463321e508' # assets
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b51b712a-f40c-4a77-b637-ef850aac7471: # text
    columnSuffix: xabonwdi
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: ContactInfo
name: 'Contact info'
sortOrder: 1
