field: 9efe4b9d-7cc3-4cf5-b8a4-a87965c93a5a # Vacature informatie
fieldLayouts:
  108b201b-be6a-4767-93df-ea1d408f9f79:
    tabs:
      -
        elements:
          -
            fieldUid: 7cc6d231-705d-4632-9b44-0ad7e83ad00c # Section subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7cc6d231-705d-4632-9b44-0ad7e83ad00c: # Section subtitle
    columnSuffix: pwtkigae
    contentColumnType: text
    fieldGroup: null
    handle: sectionSubtitle
    instructions: ''
    name: 'Section subtitle'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: vacatureSectionSubtitle
name: 'Vacature section subtitle'
sortOrder: 2
