field: 9efe4b9d-7cc3-4cf5-b8a4-a87965c93a5a # Vacature informatie
fieldLayouts:
  1da63de5-3be9-4e27-a328-6ac5cfceca8b:
    tabs:
      -
        elements:
          -
            fieldUid: 27c5d190-c165-4b03-b184-5d8f19b4c1e5 # Section title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  27c5d190-c165-4b03-b184-5d8f19b4c1e5: # Section title
    columnSuffix: dbnmkdmu
    contentColumnType: text
    fieldGroup: null
    handle: sectionTitle
    instructions: ''
    name: 'Section title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: vactureSectionTitle
name: 'Vacature section title'
sortOrder: 1
