fieldLayouts:
  49fb0554-e985-4fae-be1e-946be4e55408:
    tabs:
      -
        elements:
          -
            fieldUid: 69f371e4-72a6-4502-8956-e95f058cb3e5 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: ef6a0cfc-3825-4c16-bec8-eb45986cb2c6 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: aanbodOverwiew
hasTitleField: false
name: 'Aanbod Overwiew'
section: f9815606-55a0-417a-b7d3-61b347c4be90 # Aanbod Overwiew
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
