fieldLayouts:
  49fb0554-e985-4fae-be1e-946be4e55408:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: ba61c9d3-f20b-4b65-bb39-001e11577fd2 # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 1ef7a627-b53e-42eb-8f24-b542d44f45b7 # cardImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 345322f5-8924-4e3a-85b5-a9db7bdcfa10 # cardTitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3387e151-0efd-4a63-b79d-0590657d081a # cardButtonText
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Card
        sortOrder: 2
handle: aanbodOverwiew
hasTitleField: true
name: 'Aanbod Overwiew'
section: f9815606-55a0-417a-b7d3-61b347c4be90 # Aanbod Overwiew
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
