fieldLayouts:
  3a6e58e2-2876-4a18-9006-1132012a4492:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: 'Vacature titel'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 1ef7a627-b53e-42eb-8f24-b542d44f45b7 # cardImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 345322f5-8924-4e3a-85b5-a9db7bdcfa10 # cardTitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3387e151-0efd-4a63-b79d-0590657d081a # cardButtonText
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Card
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 9efe4b9d-7cc3-4cf5-b8a4-a87965c93a5a # Vacature informatie
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 962a4de7-c115-4643-ad6e-73cf143efccf
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Vacature inhoud'
        sortOrder: 2
handle: default
hasTitleField: true
name: Default
section: c12eda79-3a9a-4866-b9df-ce89c0124591 # vacatures
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
