fieldLayouts:
  1a89d43d-4a38-43dd-943c-0a30c6e20891:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: ba61c9d3-f20b-4b65-bb39-001e11577fd2 # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4cf63765-8ef6-429e-af42-e5301205d864 # Profession
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b78255e8-d163-4080-bcf9-b103c6d48b19 # Personal Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'detail page content'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 1ef7a627-b53e-42eb-8f24-b542d44f45b7 # cardImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 345322f5-8924-4e3a-85b5-a9db7bdcfa10 # cardTitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3387e151-0efd-4a63-b79d-0590657d081a # cardButtonText
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: card
        sortOrder: 2
handle: default
hasTitleField: true
name: Default
section: 081cf9f3-bf92-4771-b575-43f3d13b773a # Ons Team
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
