fieldLayouts:
  406a3cf0-9812-4314-8ddb-e705efb91733:
    tabs:
      -
        elements:
          -
            fieldUid: 1ef7a627-b53e-42eb-8f24-b542d44f45b7 # cardImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 345322f5-8924-4e3a-85b5-a9db7bdcfa10 # cardTitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3387e151-0efd-4a63-b79d-0590657d081a # cardButtonText
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: default
hasTitleField: true
name: Default
section: 22054a9e-cad5-42f0-ac5b-48a8a2c0c5c3 # Homepage Categories
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
