fieldLayouts:
  0ebbafb1-eaf1-4ed6-b612-aa024aec1b4f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: HomepageSponsor
hasTitleField: true
name: 'Homepage Sponsor'
section: e3485094-16f6-4b6b-99ef-a35bb1bc4fd5 # Homepage Sponsors
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
