fieldLayouts:
  c7935b08-f56e-43f7-9f23-91689d752df1:
    tabs:
      -
        elements:
          -
            fieldUid: 3073bef6-89df-487d-954d-5500268f9706 # Melding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: melding
        sortOrder: 1
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 4f1cbcaf-6c05-4000-9f90-3c0abe53704d # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6e006b4d-da92-4d85-9241-2e0904a8f6cd # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 2
      -
        elements:
          -
            fieldUid: d909cfa3-b155-404b-80ca-b857ebb84802 # Sponsors
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Sponsors
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 3fe36747-cd19-43f4-ab43-3990abff9e6f # Card
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: categorieën
        sortOrder: 4
handle: homepage
hasTitleField: true
name: Homepage
section: 0c29af0a-a0a3-4472-b6c2-51f0809f33d1 # Homepage
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
