fieldLayouts:
  0ebbafb1-eaf1-4ed6-b612-aa024aec1b4f:
    tabs:
      -
        elements:
          -
            fieldUid: d909cfa3-b155-404b-80ca-b857ebb84802 # Sponsors
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: HomepageSponsor
hasTitleField: true
name: 'Homepage Sponsor'
section: e3485094-16f6-4b6b-99ef-a35bb1bc4fd5 # Homepage Sponsors
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
