fieldLayouts:
  3caf75be-b2e8-4379-86b0-2fa5368a96b3:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: ba61c9d3-f20b-4b65-bb39-001e11577fd2 # Intro
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 3fe36747-cd19-43f4-ab43-3990abff9e6f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Card
        sortOrder: 2
handle: vacaturesOverview
hasTitleField: true
name: 'Vacatures overview'
section: 2f02eede-a297-4a5f-8f80-87e56651c99b # Vacatures overview
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
