columnSuffix: rrjwpygc
contentColumnType: text
fieldGroup: 37a2a072-4acf-42ca-a032-cd323c6baaae # Common
handle: button
instructions: ''
name: Button
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
