columnSuffix: bguzpdcx
contentColumnType: text
fieldGroup: 37a2a072-4acf-42ca-a032-cd323c6baaae # Common
handle: cardTitle
instructions: ''
name: cardTitle
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
