columnSuffix: null
contentColumnType: string
fieldGroup: 37a2a072-4acf-42ca-a032-cd323c6baaae # Common
handle: card
instructions: ''
name: Card
searchable: false
settings:
  contentTable: '{{%matrixcontent_card}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
