columnSuffix: fxiapaat
contentColumnType: text
fieldGroup: 2bd3e48e-5ee8-4734-b299-8960433eabd0 # Contactinfo
handle: openingsuren
instructions: ''
name: openingsuren
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
