columnSuffix: tebmyrwd
contentColumnType: string
fieldGroup: 37a2a072-4acf-42ca-a032-cd323c6baaae # Common
handle: sponsors
instructions: 'Sponsors section title'
name: Sponsors
searchable: true
settings:
  contentTable: '{{%matrixcontent_sponsors}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
