dateModified: 1653748300
email:
  fromEmail: rik.vandenheede0@hotmail.com
  fromName: dat_vzw
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0c29af0a-a0a3-4472-b6c2-51f0809f33d1: Homepage # Homepage
    0fff5538-00fa-45ce-949b-5f7a7b493361: 'homepage Card' # homepage Card
    1d9b20df-154e-4312-ad01-5d94eb217809: Contact # Contact
    2f02eede-a297-4a5f-8f80-87e56651c99b: 'Vacatures overview' # Vacatures overview
    4f1cbcaf-6c05-4000-9f90-3c0abe53704d: Subtitle # Subtitle
    5c47d6c5-8f0d-4d83-945a-f20a48a5387c: 'Homepage Cards' # Homepage Cards
    6e006b4d-da92-4d85-9241-2e0904a8f6cd: Paragraph # Paragraph
    7ce33ffe-39c3-4e09-a3b0-993c7187a718: Homepage # Homepage
    0036f8cb-73f6-426c-962b-f39d99c441f4: Button # Button
    37a2a072-4acf-42ca-a032-cd323c6baaae: Common # Common
    46f2d4d1-ce5b-4c81-9426-b501551eb2de: 'Vacatures overview' # Vacatures overview
    66c31483-7f68-4b9a-8a8f-f0316059563d: 'Contact Form' # Contact Form
    71de84fd-bd15-448e-a05f-1ce4576c49c9: 'Contact Aarschot' # Contact Aarschot
    87db7015-5296-4b55-878d-f472d21686f7: Default # Default
    139e1254-e8ca-48b0-a68a-3545a105e1ea: dat_vzw # dat_vzw
    386196f2-464b-45fb-aa90-7167868ac034: 'Homepage Sponsor' # Homepage Sponsor
    a390452f-2409-4f3b-a9bd-61d5555f8a6d: HeroImage # HeroImage
    b38d8e60-f5e0-4182-9c15-6ed75c6ace53: 'Public Schema' # Public Schema
    ba61c9d3-f20b-4b65-bb39-001e11577fd2: Intro # Intro
    ba92d822-4196-43fb-b713-78499f587a0c: Blog # Blog
    c059b647-3868-4e91-9c7e-a0b34036f257: 'Contact Tienen' # Contact Tienen
    c12eda79-3a9a-4866-b9df-ce89c0124591: vacatures # vacatures
    c81b6045-dcd0-401d-9cbc-326376bc872c: dat_vzw # dat_vzw
    cbcb4f40-1260-4047-9d2a-9ae47c2977db: New # New
    d58adfb1-7bb4-4606-9428-3499d791b8b3: Default # Default
    d909cfa3-b155-404b-80ca-b857ebb84802: Sponsors # Sponsors
    e3e9a72f-1058-44c6-93a0-dc88aed4c0c3: 'Contact Tienen' # Contact Tienen
    e94f01f6-b17f-406d-90ce-dba20a0474f4: 'Contact Aarschot' # Contact Aarschot
    e3485094-16f6-4b6b-99ef-a35bb1bc4fd5: 'Homepage Sponsors' # Homepage Sponsors
    fec971fd-7f13-4818-8bbc-4b497a1f6e78: Contact # Contact
plugins:
  formie:
    edition: standard
    enabled: true
    licenseKey: 4P07E5QIG4OKWGVA3N8CYKTQ
    schemaVersion: 1.2.8
  navigate:
    edition: standard
    enabled: true
    licenseKey: P98GQ2VFS2Z6KCMR95ZRVJUR
    schemaVersion: 2.4.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: dat_vzw
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
