defaultPlacement: end
enableVersioning: true
handle: aanbodOverwiew
name: 'Aanbod Overwiew'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  139e1254-e8ca-48b0-a68a-3545a105e1ea:
    enabledByDefault: true
    hasUrls: true
    template: _aanbod\_index.twig
    uriFormat: aanbod-overwiew
type: single
