defaultPlacement: end
enableVersioning: true
handle: sponsors
name: Sponsors
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  139e1254-e8ca-48b0-a68a-3545a105e1ea: # dat_vzw
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
