defaultPlacement: end
enableVersioning: true
handle: vacatures
name: vacatures
propagationMethod: all
siteSettings:
  139e1254-e8ca-48b0-a68a-3545a105e1ea: # dat_vzw
    enabledByDefault: true
    hasUrls: true
    template: _vacatures/_entry
    uriFormat: 'vacatures/{slug}'
type: channel
